import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';

import {inventario} from '../data/inventario'

export default class Home extends React.Component {
  
  constructor(props){
    super(props);
    this.state = {
      inputSearch: '',
      filteredItems: [],
      producto: '',
      precio: 0,
      cantidad: 0,
      codigo: 0
    }
    this.inventario = inventario;

    // vinculacion funciones con la clase
    this.handleChange = this.handleChange.bind(this);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.filterItem = this.filterItem.bind(this);
  }

  // filtrado de productos dependiendo del texto que recibe
  filterItem(texto, attr = "name"){
    
    if (attr == "name"){
      let splitWord = texto.split(' ');
      let words = '.*'
      for (let i = 0; i < splitWord.length; i++) {
        words += String(splitWord[i].toLowerCase()+'.*');
      }
      let reg = new RegExp(String(`${texto.toLowerCase()}|${words}`), "g");
      let f = this.inventario.filter((item)=>(
        // aplica el regex a los nombres de productos
        item[attr].toLowerCase().match(reg)
        ))
      // devuelve los primeros cuatro elementos del array
      return f.slice(0, 6)
    } else {
      let f = this.inventario.filter((item)=>(
        item[attr] == texto
      ))
      return f
    }
  }

  // cambiar estado cuando se modifica las etiquetas `input`
  handleChange(event) {
    
    const target = event.target;
    const name = target.name;
    
    /*si es la etiqueta de `inputSearch` la que se modifica. se realiza el filtrado de los productos
    si los productos resultantes mayor que cero, entonces actualiza todo, y las variables de producto, precio y cantidad
    se llenara con los valor del primer producto devuelto del array. 
    Si no hay resultados, solo se actualiza inputSeach y los productos filtrados (vacio)*/
    if (name == 'inputSearch') {
      const fil_items = this.filterItem(event.target.value);
      
      if (fil_items.length > 0) {
        this.setState({
          inputSearch: event.target.value,
          filteredItems: fil_items,
          producto: fil_items[0].name,
          precio: fil_items[0].precio,
          cantidad: fil_items[0].cantidad,
          codigo: fil_items[0].codigo
        })
      } else {
        this.setState({
          inputSearch: event.target.value,
          filteredItems: fil_items
        })
      }
    } else if (name == 'lista') {
      // cuando se seleccione un elemento de la lista desplegada de los elemtnos filtrados, se hace una busqueda con el
      // valor EXACTO del producto (por tanto, se devolvera un solo producto)
      const fil_items = this.filterItem(event.target.value);
      this.setState({
        inputSearch: event.target.value,
        filteredItems: fil_items,
        producto: fil_items[0].name,
        precio: fil_items[0].precio,
        cantidad: fil_items[0].cantidad,
        codigo: fil_items[0].codigo
      })
    } else {
      this.setState({
        [name]: event.target.value
      })
    }
  }

  handleSubmit(event) {
    
    if (this.state.producto != '' && this.state.precio != 0 && this.state.cantidad != 0){
      console.log(this.state.codigo)
      let v_codigo;
      if (this.filterItem(this.state.codigo, 'codigo')[0]['name']!==this.state.producto){
        v_codigo = 0;
      } else {
        v_codigo = this.state.codigo;
      }
  
      const data = {
        codigo: v_codigo,
        producto: this.state.producto,
        precio: this.state.precio,
        cantidad: this.state.cantidad,
        "created at": new Date()
      }
      console.log(data);
      fetch("https://sheet.best/api/sheets/24c38baf-e24d-42e6-acf4-97d73a5944ae",
      {
        method: "POST",
        mode: "cors",
        headers: {
          "Content-type": "application/json"
        },
        body: JSON.stringify(data),
      })
        .then((r) => r.json())
        .then((data)=>{
          console.log(data);
        })
        .catch((error)=>{
          console.log(error);
        });
  
      this.setState({
        inputSearch: '',
        filteredItems: [],
        producto: '',
        precio: 0,
        cantidad: 0,
        codigo: 0
      })
    } else {
      alert('Valores en blanco detectados');
    }

    event.preventDefault();
  }

  render() {
    return (
      <div>
        <Head>
          <title>Creditodo inventario</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1>
            Inventario Creditodo 2021
          </h1>
          <form onSubmit={this.handleSubmit}>
            <label>
            Buscar: 
              <input type="text" 
                value={this.state.inputSearch} 
                onChange={this.handleChange} 
                name="inputSearch"
                placeholder="Busca tu producto aquí"/>
            </label>
            <div> 
              {this.state.filteredItems.map( (item) => (
                <div key={item.codigo}>
                  <input type="radio"  name="lista" value={item.name} onChange={this.handleChange} /> {item.name}
                </div>
                )
              )}
            </div>
            <label>Producto:</label>
            <input type="text" value={this.state.producto} onChange={this.handleChange} name="producto" /><br />
            <label>Precio:</label>
            <input type="text" value={this.state.precio} onChange={this.handleChange} name="precio"/><br />
            <label>Cantidad:</label>
            <input type="text" value={this.state.cantidad} onChange={this.handleChange} name="cantidad" /><br />
            <input type="submit" value="Submit" />
          </form>
        </main>  
      </div>
    )  
  }
}
